import { BadgeCheck, CheckCheck, CircleHelp, CircleX, Eye, Lightbulb, Quote, Sparkles } from "lucide-react";

import { Tooltip } from "@/components/ui/menu";
import { cn } from "@/lib/utils";

export const STATUS = {
  confirmed_by_source: {
    label: "Confirmed by source",
    icon: BadgeCheck,
    className: "border-st-confirmed/60 text-st-confirmed bg-st-confirmed/10",
    help: "A cited source directly states this.",
  },
  corroborated: {
    label: "Corroborated",
    icon: CheckCheck,
    className: "border-st-corroborated/60 text-st-corroborated bg-st-corroborated/10",
    help: "Supported by at least two independent sources.",
  },
  unverified: {
    label: "Unverified",
    icon: CircleHelp,
    className: "border-st-unverified/60 text-st-unverified bg-st-unverified/10",
    help: "Not yet verified by an investigator.",
  },
  contradicted: {
    label: "Contradicted",
    icon: CircleX,
    className: "border-st-contradicted/60 text-st-contradicted bg-st-contradicted/10",
    help: "At least one source contradicts this.",
  },
  ai_hypothesis: {
    label: "AI hypothesis",
    icon: Sparkles,
    className: "border-dashed border-st-ai/70 text-st-ai bg-st-ai/10",
    help: "Suggested by AI; never an established fact until verified.",
  },
} as const;

export const PROVENANCE = {
  observed: {
    label: "Observed",
    icon: Eye,
    className: "border-pv-observed/70 text-pv-observed",
    help: "Observed directly by Angel Engine (e.g. image analysis).",
  },
  source_reported: {
    label: "Source-reported",
    icon: Quote,
    className: "border-double border-[3px] border-pv-reported/70 text-pv-reported py-0",
    help: "Reported by a public source; not independently observed.",
  },
  analyst_inference: {
    label: "Analyst inference",
    icon: Lightbulb,
    className: "border-dotted border-pv-inference/70 text-pv-inference",
    help: "An investigator's inference from the cited evidence.",
  },
  ai_hypothesis: {
    label: "AI hypothesis",
    icon: Sparkles,
    className: "border-dashed border-st-ai/70 text-st-ai",
    help: "Generated by AI and labelled as such permanently.",
  },
} as const;

export type Status = keyof typeof STATUS;
export type Provenance = keyof typeof PROVENANCE;

function BadgeShell({
  icon: Icon,
  label,
  className,
  help,
  size = "md",
}: {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
  className: string;
  help: string;
  size?: "sm" | "md";
}) {
  return (
    <Tooltip content={help}>
      <span
        tabIndex={0}
        className={cn(
          "badge inline-flex items-center gap-1 rounded-sm border font-medium whitespace-nowrap",
          size === "sm" ? "px-1 py-px text-[11px]" : "px-1.5 py-0.5 text-xs",
          className,
        )}
      >
        <Icon className={size === "sm" ? "h-3 w-3" : "h-3.5 w-3.5"} aria-hidden />
        {label}
      </span>
    </Tooltip>
  );
}

export function VerificationStatusBadge({ status, size }: { status: string; size?: "sm" | "md" }) {
  const meta = STATUS[status as Status] ?? STATUS.unverified;
  return <BadgeShell {...meta} size={size} />;
}

export function ProvenanceBadge({ provenance, size }: { provenance: string; size?: "sm" | "md" }) {
  const meta = PROVENANCE[provenance as Provenance] ?? PROVENANCE.observed;
  return <BadgeShell {...meta} size={size} />;
}

export function ConfidenceLevel({ confidence }: { confidence?: { level: string; basis?: string | null } | null }) {
  if (!confidence) return <span className="text-subtle">n/a</span>;
  const bars = { low: 1, moderate: 2, high: 3 }[confidence.level] ?? 0;
  return (
    <Tooltip content={confidence.basis ? `Basis: ${confidence.basis}` : "No basis recorded"}>
      <span tabIndex={0} className="inline-flex items-center gap-1.5 text-xs whitespace-nowrap">
        <span aria-hidden className="flex items-end gap-0.5">
          {[1, 2, 3].map((n) => (
            <span
              key={n}
              className={cn("w-1 rounded-sm", n <= bars ? "bg-foreground/80" : "bg-border-strong/40")}
              style={{ height: `${4 + n * 3}px` }}
            />
          ))}
        </span>
        <span className="capitalize">{confidence.level}</span>
      </span>
    </Tooltip>
  );
}

export function CitationChip({
  label,
  title,
  onClick,
}: {
  label: string;
  title?: string;
  onClick?: () => void;
}) {
  const className =
    "inline-flex items-center rounded-sm border border-primary/40 bg-primary/10 px-1 font-mono text-[11px] font-semibold text-primary hover:bg-primary/20";
  return onClick ? (
    <button type="button" className={className} onClick={onClick} title={title} aria-label={`Evidence ${label}`}>
      {label}
    </button>
  ) : (
    <span className={className} title={title}>
      {label}
    </span>
  );
}
