/** Hierarchical query keys so a change can invalidate exactly what depends on it. */
export const qk = {
  session: ["session"] as const,
  investigations: (filters?: object) => ["investigations", "list", filters ?? {}] as const,
  investigation: (id: string) => ["investigations", id] as const,
  dashboard: (id: string) => ["investigations", id, "dashboard"] as const,
  findings: (id: string, filters?: object) => ["investigations", id, "findings", filters ?? {}] as const,
  finding: (id: string, findingId: string) => ["investigations", id, "finding", findingId] as const,
  evidence: (id: string, filters?: object) => ["investigations", id, "evidence", filters ?? {}] as const,
  evidenceItem: (id: string, evidenceId: string) => ["investigations", id, "evidence-item", evidenceId] as const,
  sources: (id: string, filters?: object) => ["investigations", id, "sources", filters ?? {}] as const,
  source: (id: string, sourceId: string) => ["investigations", id, "source", sourceId] as const,
  runs: (id: string) => ["investigations", id, "runs"] as const,
  run: (id: string, runId: string) => ["investigations", id, "run", runId] as const,
  connectors: (id: string) => ["investigations", id, "connectors"] as const,
  suggestions: (id: string) => ["investigations", id, "suggestions"] as const,
  images: (id: string) => ["investigations", id, "images"] as const,
  image: (id: string, imageId: string) => ["investigations", id, "image", imageId] as const,
  clues: (id: string, imageId: string) => ["investigations", id, "image", imageId, "clues"] as const,
  similar: (id: string, imageId: string) => ["investigations", id, "image", imageId, "similar"] as const,
  timeline: (id: string, filters?: object) => ["investigations", id, "timeline", filters ?? {}] as const,
  graph: (id: string, filters?: object) => ["investigations", id, "graph", filters ?? {}] as const,
  activity: (id: string) => ["investigations", id, "activity"] as const,
  notes: (id: string, target?: object) => ["investigations", id, "notes", target ?? {}] as const,
  reports: (id: string) => ["investigations", id, "reports"] as const,
  report: (id: string, reportId: string) => ["investigations", id, "report", reportId] as const,
  exports: (id: string, reportId: string) => ["investigations", id, "report", reportId, "exports"] as const,
  assistant: (id: string) => ["investigations", id, "assistant"] as const,
  interaction: (id: string, interactionId: string) => ["investigations", id, "assistant", interactionId] as const,
  proposals: (id: string) => ["investigations", id, "proposals"] as const,
  members: (id: string) => ["investigations", id, "members"] as const,
  retention: (id: string) => ["investigations", id, "retention"] as const,
};
