"""All ORM models (imported here so Alembic and the application see the full metadata)."""

from angel_engine.db.models.evidence import (
    CollectionRun,
    EvidenceItem,
    Fact,
    Finding,
    FindingEvidence,
    FindingStatusHistory,
    Source,
    Suggestion,
)
from angel_engine.db.models.graph import (
    Entity,
    EntityMention,
    Relationship,
    RelationshipEvidence,
    RelationshipStatusHistory,
    TimelineEvent,
    TimelineEventEvidence,
)
from angel_engine.db.models.identity import Attestation, LegalDocument, RecoveryCode, User, UserSession
from angel_engine.db.models.images import Image, ImageAnalysis, ImageClue, ImageHash
from angel_engine.db.models.investigations import (
    DataKey,
    Investigation,
    InvestigationMember,
    InvestigationRefCounter,
    OversightGrant,
)
from angel_engine.db.models.platform import (
    AbuseReport,
    AuditAnchor,
    AuditChainHead,
    AuditLog,
    BlobDeletion,
    DataExport,
    IdempotencyKey,
    Job,
    PeriodicSchedule,
    PolicyDecision,
    Setting,
)
from angel_engine.db.models.work import AIInteraction, AIProposal, Note, Report, ReportExport

#: Tables protected by row-level security (investigation-scoped content).
RLS_TABLES: tuple[str, ...] = (
    "sources",
    "collection_runs",
    "evidence_items",
    "findings",
    "finding_evidence",
    "finding_status_history",
    "facts",
    "suggestions",
    "entities",
    "entity_mentions",
    "relationships",
    "relationship_evidence",
    "relationship_status_history",
    "timeline_events",
    "timeline_event_evidence",
    "images",
    "image_hashes",
    "image_analyses",
    "image_clues",
    "notes",
    "reports",
    "report_exports",
    "ai_interactions",
    "ai_proposals",
)

__all__ = [
    "RLS_TABLES",
    "AIInteraction",
    "AIProposal",
    "AbuseReport",
    "Attestation",
    "AuditAnchor",
    "AuditChainHead",
    "AuditLog",
    "BlobDeletion",
    "CollectionRun",
    "DataExport",
    "DataKey",
    "Entity",
    "EntityMention",
    "EvidenceItem",
    "Fact",
    "Finding",
    "FindingEvidence",
    "FindingStatusHistory",
    "IdempotencyKey",
    "Image",
    "ImageAnalysis",
    "ImageClue",
    "ImageHash",
    "Investigation",
    "InvestigationMember",
    "InvestigationRefCounter",
    "Job",
    "LegalDocument",
    "Note",
    "OversightGrant",
    "PeriodicSchedule",
    "PolicyDecision",
    "RecoveryCode",
    "Relationship",
    "RelationshipEvidence",
    "RelationshipStatusHistory",
    "Report",
    "ReportExport",
    "Setting",
    "Source",
    "Suggestion",
    "TimelineEvent",
    "TimelineEventEvidence",
    "User",
    "UserSession",
]
