"use client";

import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Copy, Download, ShieldCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";

import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/data";
import { Alert, LoadingBlock } from "@/components/ui/feedback";
import { Checkbox, Field, Input } from "@/components/ui/form";
import { api, unwrap } from "@/lib/api/client";
import { messageOf } from "@/lib/api/errors";
import { SESSION_KEY, gateFor, useSession } from "@/lib/session";

export function MfaSetup() {
  const router = useRouter();
  const client = useQueryClient();
  const { data: session, isPending } = useSession();
  const [code, setCode] = useState("");
  const [codes, setCodes] = useState<string[] | null>(null);
  const [saved, setSaved] = useState(false);
  const started = useRef(false);

  const enroll = useMutation({ mutationFn: () => unwrap(api.POST("/api/v1/auth/mfa/enroll")) });
  const confirm = useMutation({
    mutationFn: () => unwrap(api.POST("/api/v1/auth/mfa/enroll/confirm", { body: { code: code.replace(/\s+/g, "") } })),
    onSuccess: (done) => {
      setCodes(done.recovery_codes);
      client.setQueryData(SESSION_KEY, done);
    },
  });

  useEffect(() => {
    if (isPending) return;
    if (!session) router.replace("/login");
    else if (session.state === "active" && !codes) router.replace(gateFor(session) ?? "/dashboard");
    else if (session.state === "mfa_enroll" && !started.current) {
      started.current = true; // one secret per visit, even when effects run twice in development
      enroll.mutate();
    }
  }, [isPending, session, codes, enroll, router]);

  if (codes) {
    const text = codes.join("\n");
    return (
      <div className="w-full max-w-lg space-y-5">
        <h1 className="text-2xl font-semibold tracking-tight">Save your recovery codes</h1>
        <Alert tone="warning">
          Each code works once if you lose your authenticator. They are shown only now — store them somewhere safe and
          offline.
        </Alert>
        <Card className="p-5">
          <ul className="grid grid-cols-2 gap-2 font-mono text-sm" aria-label="Recovery codes">
            {codes.map((c) => (
              <li key={c} className="rounded bg-surface-2 px-2 py-1 text-center">{c}</li>
            ))}
          </ul>
          <div className="mt-4 flex flex-wrap gap-2">
            <Button size="sm" onClick={() => void navigator.clipboard.writeText(text)}>
              <Copy className="h-4 w-4" aria-hidden /> Copy
            </Button>
            <Button
              size="sm"
              onClick={() => {
                const url = URL.createObjectURL(new Blob([text + "\n"], { type: "text/plain" }));
                const a = document.createElement("a");
                a.href = url;
                a.download = "angel-engine-recovery-codes.txt";
                a.click();
                URL.revokeObjectURL(url);
              }}
            >
              <Download className="h-4 w-4" aria-hidden /> Download
            </Button>
          </div>
        </Card>
        <Checkbox label="I have saved my recovery codes." checked={saved} onChange={(e) => setSaved(e.target.checked)} />
        <Button
          variant="primary"
          disabled={!saved}
          onClick={() => {
            const current = client.getQueryData(SESSION_KEY) as Parameters<typeof gateFor>[0];
            router.replace(gateFor(current) ?? "/dashboard");
          }}
        >
          Continue
        </Button>
      </div>
    );
  }

  return (
    <div className="w-full max-w-lg space-y-5">
      <div className="space-y-1">
        <h1 className="text-2xl font-semibold tracking-tight">Set up multi-factor authentication</h1>
        <p className="text-sm text-muted">
          Every Angel Engine account uses an authenticator app (TOTP). Scan the code, then enter the 6-digit code it shows.
        </p>
      </div>
      {enroll.isPending || isPending ? <LoadingBlock label="Preparing your authenticator code" /> : null}
      {enroll.isError ? <Alert tone="danger">{messageOf(enroll.error)}</Alert> : null}
      {enroll.data ? (
        <Card className="space-y-4 p-5">
          <div className="flex flex-col items-center gap-3 sm:flex-row sm:items-start">
            {/* eslint-disable-next-line @next/next/no-img-element -- generated by the API as a data URI */}
            <img src={enroll.data.qr_data_uri} alt="QR code for your authenticator app" className="h-44 w-44 rounded bg-white p-2" />
            <div className="space-y-2 text-sm">
              <p className="text-muted">Can&apos;t scan? Enter this key manually:</p>
              <p className="font-mono text-base break-all select-all">{enroll.data.secret}</p>
            </div>
          </div>
          <form
            className="space-y-3"
            onSubmit={(e) => {
              e.preventDefault();
              confirm.mutate();
            }}
          >
            <Field label="6-digit code">
              {(p) => (
                <Input {...p} inputMode="numeric" autoComplete="one-time-code" value={code} onChange={(e) => setCode(e.target.value)} className="font-mono tracking-[0.3em]" />
              )}
            </Field>
            {confirm.isError ? <Alert tone="danger">{messageOf(confirm.error)}</Alert> : null}
            <Button type="submit" variant="primary" loading={confirm.isPending}>
              <ShieldCheck className="h-4 w-4" aria-hidden /> Turn on
            </Button>
          </form>
        </Card>
      ) : null}
    </div>
  );
}
